### PR TITLE
implement warnings as described in NeXus manual

### LINKED ISSUE #14: implement warnings as advised in NeXus manual
the search:
http://download.nexusformat.org/doc/html/search.html?q=warning&check_keywords=yes&area=default

Actually, flag them as NOTE unless WARN is compelling

### PR DESCRIPTION
**Pull request by prjemian**
- FIX #14

Start with unit tests from previous generation of this code.

https://manual.nexusformat.org/search.html?q=warning

### CODE REVIEW

**Review by carterbox — COMMENTED** [review]
test_naming_conventions__issue_65 doesn't have documentation, so I'm not sure exactly what it is doing. I think it does more than just check that @ symbols are disallowed in attribute names, but I'm not sure.

**Comment by prjemian** [comment]
I, too, was wondering about the scope of this test function: `test_naming_conventions__issue_65()`.  #65 is about attributes that start with `@`.  The existing cover that intent but also go beyond that, testing incorrect names in attributes and fields.  The TODO items appear to go even further, so they can probably be deleted (or moved to some other place where they might be used).

**Comment by prjemian** [comment]
And there are merge conflicts to be resolved.

**Comment by prjemian** [comment]
@carterbox : Merge conflicts resolved. Added docstring to `test_naming_conventions__issue_65()` function.  Ready for review.

**Comment by carterbox** [comment]
I'm still confused.

```
        ["v2018.5", 99, "/entry@NX_class", "OK", "validItemName", "pattern: NX.+"],
        ["v2018.5", 99, "/entry@default", "OK", "validItemName", "strict pattern: [a-z_][a-z0-9_]*"],
        ["v2018.5", 99, "/entry/data@NX_class", "OK", "validItemName", "pattern: NX.+"],
        ["v2018.5", 99, "/entry/data@signal", "OK", "validItemName", "strict pattern: [a-z_][a-z0-9_]*"],
```
Why are these names marked as 'OK' if `@` is not allowed in the Nexus names?

**Comment by prjemian** [comment]
The string`"/entry@NX_class"` refers to HDF5 address `/entry` with attribute named `NX_class`.  The first `@` is a compact representation agreed upon within NeXus to mean "has attribute with name that follows this `a` symbol".

[NeXus manual](https://manual.nexusformat.org/preface.html) page describes this use.

**Review by carterbox — APPROVED** [review]

**Comment by prjemian** [comment]
@carterbox Thanks!

**Pull request merged**
