### PR TITLE
DOC: Remove Depsy badge from GitHub README

### PR DESCRIPTION
**Pull request by carterbox**
The Depsy project appears to be EOL. Otherwise, it is misconfigured for punx because the PyPI page is active, so I have removed the Depsy badge. The zenodo badge now links to the "all-versions" DOI.

refs #138

### CODE REVIEW

**Comment by prjemian** [comment]
I agree this can be removed.  Is there other work to be done?

**Comment by carterbox** [comment]
Page in this PR looks good to me. Not going to reformat to markdown unless there are some big formatting changes that need to be done simultaneously.

**Review by prjemian — APPROVED** [review]
@carterbox LGTM, Thanks!

**Comment by prjemian** [comment]
@carterbox Merge when ready

**Pull request merged**
