### PR TITLE
Clarify message from validate's unrecognized subcommands

### LINKED ISSUE #8: make MyArgumentParser.parse_args() more robust
make more robust for variations in optional commands

current assumption is that sys.argv[1] has the subcommand

It is possible to add arguments to the main parser that add optional arguments which may precede a subcommand.

### PR DESCRIPTION
**Pull request by prjemian**
- FIX #8

### CODE REVIEW

**Comment by prjemian** [comment]
Also need to set a default `args.file_set_name` when running `punx demonstrate`.

**Comment by prjemian** [comment]
@carterbox This is ready for review.  Also fixed `punx demonstrate` and switched a couple strings nearby to f-strings.

**Review by carterbox — APPROVED** [review]
I haven't run this code, but the updated messages seem good.

**Comment by prjemian** [comment]
@carterbox Thanks!

**Pull request merged**
